AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/StringLiteralsInInterpolation:
  Enabled: true


Layout/LineLength:
  Max: 125

Style/Documentation:
  Enabled: false